{% set version = "1.0.0" %}

package:
  name: face_alignment
  version: {{ version }}

source:
  path: ..

build:
  script_env:
   - CONDA_BUILD_PATH
  number: 1
  noarch: generic
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools
    - python
  run:
    - python
    - pytorch
    - numpy
    - scikit-image
    - scipy
    - opencv
    - tqdm

about:
  home: https://github.com/1adrianb/face-alignment
  license: BSD
  license_file: LICENSE
  summary: A face alignment libray in python

extra:
  recipe-maintainers:
    - 1adrianb
